### ISSUE TITLE
运行时出现了异常: 'PNDMScheduler' object has no attribute 'init_noise_sigma'

### ISSUE THREAD

**Issue by lktoken** [k-l-lambda/diffusers-web#1]
最新master分支，miniconda3环境，ubuntu机器上运行出现了下面的问题，
`[2022-11-30 14:29:30,395] ERROR in app: Exception on /paint-by-text [GET]
Traceback (most recent call last):
  File "/condapath/miniconda3/envs/torch/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/condapath/miniconda3/envs/torch/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/condapath/miniconda3/envs/torch/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/condapath/miniconda3/envs/torch/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/data/python/diffusers-web/main.py", line 88, in paintByText
    result = pipe.generate([prompt] * multi, num_inference_steps=n_steps, width=width, height=height)
  File "/condapath/miniconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/var/data/python/diffusers-web/pipeline_stable_diffusion.py", line 339, in generate
    latents = latents * self.scheduler.init_noise_sigma
AttributeError: 'PNDMScheduler' object has no attribute 'init_noise_sigma'
127.0.0.1 - - [30/Nov/2022 14:29:30] "GET /paint-by-text?prompt=beauty&multi=1&n_steps=50&w=512&h=512 HTTP/1.1" 500 -`
希望能帮忙解答

**Comment by k-l-lambda** [comment]
master 分支需要升级diffusers版本到0.6.0．develop分支升级到0.9.0．修复已提交．
